export const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  SEARCH_PAGE: "/search-page",
  HOW_WORK: "/how-work",
  HOW_WORK_DRIVER: "/how-work/how-driver",
  HOW_WORK_PASSENGER: "/how-work/how-passenger",
  SELECTED_DRIVER: "/selected-driver",
  PUBLISH_PAGE: "/publish-page",
  PUBLISH_PAGE_SUCCESSS: "/publish-page/success-publish-page",
  USER_PROFILE: "/user-profile/*",
  CHAT: "/chat",
  ERROR: "*",
};
